Elite Dangerous logfile watcher thread fix
Aurora-RGB/Aurora pull request #126
Opened 2023-01-24 22:33 UTC by DoorKip

This PR fixes an issue that prevents logfile watcher threads from starting correctly in the EliteDangerous profile, due to the running flag not being set at thread start. This was causing the profiles lighting layers to not update correctly on in-game events.

Also fixes a related spelling error.

2023-01-24 22:41 UTC, Aytackydln requested changes

2023-01-24 22:41 UTC, Aytackydln commented on Project-Aurora/Project-Aurora/Profiles/EliteDangerous/Helpers/FileWatcher.cs
> +                while  running)
isn't this a typo?

2023-01-25 00:13 UTC, DoorKip commented on Project-Aurora/Project-Aurora/Profiles/EliteDangerous/Helpers/FileWatcher.cs
> +                while  running)
Yep. Good catch. Fixed.

2023-01-25 07:20 UTC, Aytackydln approved these changes

2023-01-25 07:20 UTC, merged